
# Are we looking at the blue arms or the red arms? E.g. CCDs 1 and 3 or CCDs 2 and 4
# Until the Hector red arm is fixed, this should be set to 'blue'
red_or_blue : 'blue'

flat_file_Hector : "/Volumes/OtherFiles/Science/Hector/Observations/220116/ccd_3/16jan30027.fits"
flat_file_AAOmega : "/Volumes/OtherFiles/Science/Hector/Observations/220116/ccd_1/16jan10027.fits"

# Now load the object file
# We need the directory where the ccd folders are (e.g. in this folder there should be ccd_1, ccd_2, ccd_3, etc)
data_dir : "/Volumes/OtherFiles/Science/Hector/Observations/220116"
# The prefix of every file- probably the date, e.g. 12jan
file_prefix : "16jan" 

# Note that these options can be overwritten from the command line
sigma_clip : True # use --sigma-clip or -s on the command line
